### ISSUE TITLE
Don't work at present time

### ISSUE THREAD

**Issue by Jurik-Phys** [delphinus/ddc-ctags#2]
After install and setup ddc-ctag gives an error into vim after trying found data for autocomplete (after typing second charset). File 'tags' exists into root of c++/qt project

> [ddc] TypeError: source.gather is not a function^@    at callSourceGather (file:///home/<username>/.vim/bundle/ddc.vim/denops/ddc/ddc.ts:1290:34)^@    at file:///home/<username>/.vim/bundle/ddc.vim/denops/ddc/ddc.ts:307:30^@    at eventL
> oopTick (ext:core/01_core.js:183:11)^@    at async Promise.all (index 0)^@    at async Ddc.gatherResults (file:///ho...///home/<username>/.vim/bundle/ddc.vim/denops/ddc/app.ts#1870.607886:315:5)^@    at async file:///home/<username>/.vim/bundle/ddc.vim/denops/ddc/app.ts#1870.607886:200:11^@    at async Lock.lock (https://deno.land/x/async@v2.0.2/lock.ts:51:14)^@    at async Object.onEvent (file:///home/<username>/.vim/bundle/ddc.vim/denops/ddc/app.ts#1870.607886:196:7)
> 

Vim - 9.0.1499
deno 1.38.0 (release, x86_64-unknown-linux-gnu)
  v8 12.0.267.1
  typescript 5.2.2
ddc.vim - 2023.07.08;
denops.vim - v5.0.0
Universal Ctags 5.9.0, Copyright (C) 2015 Universal Ctags Team

Help me, I need to automatically complete names of methods in my classes

**Comment by Shougo** [comment]
Unfortunately, this source is too old(it is two years ago).
And latest ddc.vim does not support it.

@delphinus Ping.

**Comment by Shougo** [comment]
Please test this.

https://github.com/delphinus/ddc-ctags/pull/3

**Comment by Jurik-Phys** [comment]
> Please test this.
> 
> #3

Just nothing

I used Vundle plugin manager
   ```
Plugin 'Shougo/ddc.vim'                           
   Plugin 'vim-denops/denops.vim'              
   Plugin 'Shougo/ddc-ui-native'           
   Plugin 'delphinus/ddc-ctags' 
   Plugin 'tani/ddc-fuzzy'
```
I installed 'delphinus/ddc-ctags' and replace ~/.vim/bundle/ddc-ctags/deonps/@ddc-sources/ctags.ts from [pull request](https://github.com/delphinus/ddc-ctags/blob/56987f3753e2652d2ce7d5f5f528026f68d87171/denops/%40ddc-sources/ctags.ts)

Set sources only 'ctags'
`call ddc#custom#patch_global('sources', [ 'ctags' ])`

Set source options
```
call ddc#custom#patch_global('sourceOptions', {
   \ '_': {
   \   'matchers': ['matcher_fuzzy'],
   \   'sorters': ['sorter_fuzzy'],
   \   'converters': ['converter_fuzzy', 'converter_remove_overlap' ],
   \ },
   \ 'ctags' : { 
     \ 'mark' : '[C]',
   \ },
   \ })
```
Also set actual path to 'ctags' 
```
call ddc#custom#patch_global('sourceParams', {
  \ 'ctags': {'executable': '/usr/bin/ctags'},
  \ })

```
In root of my project I have actual ctag file with name "tags"

When I typing "socket->wr" in projects *.cpp file nothing to do, no pop-up menu. 

When I manual pressing <Ctrl-x><Ctrl-]> internal vim autocomplete arise pop-up menu with "writeData", "writeError", "writeHeaders" and other words for inserted.

Where can I read about debugging this plugin? I don't understand where to look for debugging information about the plugin's operation.

**Comment by Shougo** [comment]
It worked for me.

```vim
set nocompatible

set runtimepath+=~/work/denops.vim
set runtimepath+=~/work/ddc.vim
set runtimepath+=~/work/ddc-ui-native
set runtimepath+=~/work/ddc-filter-matcher_head
set runtimepath+=~/work/ddc-filter-sorter_rank
set runtimepath+=~/src/ddc-ctags

call ddc#custom#patch_global('sources', ['ctags'])
call ddc#custom#patch_global('ui', 'native')
call ddc#custom#patch_global('sourceOptions', {
   \   '_': {
   \     'matchers': ['matcher_head'],
   \     'sorters': ['sorter_rank'],
   \   },
   \   'ctags' : {
   \     'mark' : '[C]',
   \   },
   \ })

call ddc#enable()

cd ~/src/vim
edit src/eval.c
```

I think you don't set `ui` option.

**Comment by Jurik-Phys** [comment]
Hm, work but very strange.

### **In some case <s>work</s>**

After write this post I see that ddc-ctags found other function no "createToyResponse" but "createToy'. All variants of "createToyResponse" was found by ddc-around-sources. Also I see that this function in first place when used native autocomplete by `<Ctrl-x><Ctrl-]>`. All autocomlete function (createToyResponse, writeHeaders) present in tags file in root of project.

- autocomplete for one source 'ctag'

> call ddc#custom#patch_global('sources', ['ctags'])

![only-ctag](https://github.com/delphinus/ddc-ctags/assets/17108626/d79bc973-38fe-435f-8c34-d8dfee48ebd1)

- autocomplete for one source 'ctag', 'around', 'buffer'

> call ddc#custom#patch_global('sources', ['ctags', 'around', 'buffer'])
![ctag_aroud_buffer](https://github.com/delphinus/ddc-ctags/assets/17108626/abdc2436-72ee-4437-8cd6-30a7b0266f7d)

- autocomplete for one source 'around', 'buffer', 'ctag'. Variant of 'around' has more priority, result of 'ctags' is hidden.
> call ddc#custom#patch_global('sources', ['around', 'buffer', 'ctags' ])
![aroud_buffer_ctag](https://github.com/delphinus/ddc-ctags/assets/17108626/6d652c62-6435-43e9-bc61-842dfb8a1a5e)

- also I can activate vim native autocomplite by `<Ctrl+x><Ctrl+]>`. The "createToyResponse" option is also there for autocomplete.
![reqObj_native](https://github.com/delphinus/ddc-ctags/assets/17108626/f9843108-cc23-45f4-837f-bf2de2acf504)

### **But in some case don't work**
- autocomplete for one source 'ctag' and I get "Just nothing" from previous message
![just nothing](https://github.com/delphinus/ddc-ctags/assets/17108626/279ef713-98a9-4474-ad99-c764f4fbf701)

- autocomplete for one source 'ctag', 'around', 'buffer'. socket->writeHeaders() not found for autocomlete by ddc-ctags
![don't-work-ddc-ctags](https://github.com/delphinus/ddc-ctags/assets/17108626/4abc4316-94ab-4892-8a7f-5f010d4e9b6d)

- native autocomlete <Ctrl+x><Ctrl+]> work for this case
![socket-native](https://github.com/delphinus/ddc-ctags/assets/17108626/ccf90185-61da-4115-8034-d0f124d8a976)

**Comment by delphinus** [comment]
Sorry for late and lacking update. #3 is merged (thx @Shougo). Is the problem solved?

**Comment by Jurik-Phys** [comment]
> Sorry for late and lacking update. #3 is merged (thx @Shougo). Is the problem solved?

No, because I experimented with version from pull request

**Comment by Shougo** [comment]
@Jurik-Phys the source seems filter the item by `the file`. To complete A.txt tag, you need to edit A.txt file.  And it is different issue.  Your original issue(ctags source does not work) is solved. It should be closed.

**Comment by Shougo** [comment]
If you have another problem, you need to create minimal config with minimal tags and minimal edit file and instructions.
